export interface Biom {
    id: number;
    name: string;
    icon: string;
    color: number[],
    discription: string;
    events: string[];
    goWest: boolean;
    goNord: boolean;
    goOst: boolean;
    goSud: boolean;
}

export const EmptyBiom: Biom = {
    id: 0.0,
    name: "",
    icon: "",
    color: [100,100,100],
    discription: "",
    events: [],
    goWest: true,
    goNord: true,
    goOst: true,
    goSud: true,
}

export const biom = [
       {   
        id: 0.0,
        name: 'Nichts',
        icon: 'nothing',
        color: [255, 255, 255],
        discription: 'Nichts',
        events: [],
        goWest: false,
        goNord: false,
        goOst: false,
        goSud: false,
       },
       {   
        id: 1.1,
        name: 'Wiese',
        icon: 'grass',
        color: [135, 167, 135],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: true,
        goNord: true,
        goOst: true,
        goSud: true,
       },
       {   
        id: 1.2,
        name: 'Blumen',
        icon: 'flower',
        color: [135, 167, 135],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: true,
        goNord: true,
        goOst: true,
        goSud: true,
       },    
       {   
        id: 1.3,
        name: 'Gebäude',
        icon: 'home',
        color: [135, 167, 135],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: false,
        goNord: false,
        goOst: false,
        goSud: true,
       },   
       {   
        id: 2.1,
        name: 'Feld',
        icon: 'sprout',
        color: [143, 156, 82],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: true,
        goNord: true,
        goOst: true,
        goSud: true,
       }, 
       {   
        id: 2.2,
        name: 'Mühle',
        icon: 'mill',
        color: [143, 156, 82],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: false,
        goNord: false,
        goOst: false,
        goSud: true,
       }, 
       {   
        id: 2.3,
        name: 'Feld',
        icon: 'sprout',
        color: [143, 156, 82],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: true,
        goNord: true,
        goOst: true,
        goSud: true,
       }, 
       {   
        id: 3.1,
        name: 'Tannenwald',
        icon: 'tree',
        color: [71, 124, 108],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: true,
        goNord: true,
        goOst: true,
        goSud: true,
       },
       {   
        id: 4.1,
        name: 'Dichter Tannenwald',
        icon: 'forest',
        color: [35, 61, 53],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: false,
        goNord: false,
        goOst: false,
        goSud: false,
       },
       {   
        id: 5.1,
        name: 'Laubwald',
        icon: 'love',
        color: [90, 115, 63],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: true,
        goNord: true,
        goOst: true,
        goSud: true,
       },
       {   
        id: 6.1,
        name: 'Dichter Laubwald',
        icon: 'love',
        color: [40, 51, 28],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: false,
        goNord: false,
        goOst: false,
        goSud: false,
       },
       {   
        id: 7.1,
        name: 'Flaches Gewässer',
        icon: 'waterFlat',
        color: [76, 132, 145],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: true,
        goNord: true,
        goOst: true,
        goSud: true,
       },
       {   
        id: 8.1,
        name: 'Fluss',
        icon: 'water',
        color: [93, 125, 172],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: false,
        goNord: false,
        goOst: false,
        goSud: false,
       },
       {   
        id: 8.2,
        name: 'Brücke',
        icon: 'brigeV',
        color: [93, 125, 172],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: false,
        goNord: true,
        goOst: false,
        goSud: true,
       },
       {   
        id: 8.3,
        name: 'Fluss',
        icon: 'brigeH',
        color: [93, 125, 172],
        discription: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean',
        events: [],
        goWest: true,
        goNord: false,
        goOst: true,
        goSud: false,
       },
    ]

 